apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-adapter-nsx-sm
  namespace: nsx-sm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smi-adapter-nsx-sm
  template:
    metadata:
      labels:
        name: smi-adapter-nsx-sm
      annotations:
        sidecar.nsx-sm.io/inject: "false"
    spec:
      serviceAccountName: smi-adapter-nsx-sm
      containers:
        - name: smi-adapter-nsx-sm
          image: layer5/smi-nsx-sm:latest
          command:
          - smi-adapter-nsx-sm
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smi-adapter-nsx-sm"
